### ISSUE TITLE
Babel v6 issue

### ISSUE THREAD

**Issue by raine** [MartinKolarik/babel-plugin-dedent#2]
Started getting this with babel v6:

```
TypeError: babel.Transformer is not a function
    at babelDedent (node_modules/babel-plugin-dedent/lib/index.js:14:9)
```

**Comment by MartinKolarik** [comment]
There's a lot of breaking changes in v6, so plugins need to be updated. I published v2.0.0 to npm, see the [README](https://github.com/MartinKolarik/babel-plugin-dedent#babel-v6) for usage details.
