### ISSUE TITLE
Plugin do seem to work alongside presets (Babel 6.3.17)

### ISSUE THREAD

**Issue by msegado** [MartinKolarik/babel-plugin-dedent#3]
From the README:

> Note that this plugin needs to be run before transform-es2015-template-literals, which is part of the es2015 preset. Currently, there's no way to do that when using presets, so you need to manually specify all transforms you want to use.

...actually, it seems to work now (I'm using Babel 6.3.17). looking at the Babel source, it seems that plugins are indeed processed before presets: 

https://github.com/babel/babel/blob/45d4e50b397d45fb39b4227c141145ad165185b8/packages/babel-core/src/transformation/file/options/option-manager.js#L206

**Comment by MartinKolarik** [comment]
Indeed, it seems to work now. I've updated the README.
